# Generated by Django 3.1.6 on 2021-05-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Normalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(choices=[('DREAMS', 'dreams'), ('UCDDB', 'uccdb'), ('MIT-BIH', 'mit-bih')], default='DREAMS', max_length=20)),
                ('apnea_type', models.CharField(choices=[('OSA', 'obstructive sleep apnea'), ('OSAHS', 'hypopnea')], default='OSA', max_length=20)),
                ('excerpt', models.IntegerField()),
            ],
        ),
    ]
