# Generated by Django 3.1.6 on 2021-05-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apnea_detection', '0002_auto_20210512_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalization',
            old_name='scale',
            new_name='scale_factor',
        ),
        migrations.AddField(
            model_name='normalization',
            name='slope_threshold',
            field=models.IntegerField(default=1),
        ),
    ]
