# Generated by Django 3.1.6 on 2021-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apnea_detection', '0003_auto_20210512_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalization',
            old_name='scale_factor',
            new_name='scale_factor_high',
        ),
        migrations.AddField(
            model_name='normalization',
            name='scale_factor_low',
            field=models.IntegerField(default=1),
        ),
    ]
