# Generated by Django 3.1.6 on 2021-05-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apnea_detection', '0005_auto_20210514_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Normalization',
        ),
        migrations.AddField(
            model_name='setup',
            name='norm',
            field=models.CharField(choices=[('Linear', 'linear'), ('Nonlinear', 'nonlinear')], default='Linear', max_length=20),
        ),
        migrations.AddField(
            model_name='setup',
            name='scale_factor_high',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='setup',
            name='scale_factor_low',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='setup',
            name='slope_threshold',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
