# Generated by Django 3.1.6 on 2021-05-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apnea_detection', '0007_auto_20210521_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size', models.PositiveIntegerField(default=32)),
                ('epochs', models.PositiveIntegerField(default=10)),
                ('positive_threshold', models.FloatField(default=0.7)),
            ],
        ),
    ]
