# Generated by Django 3.1.6 on 2021-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apnea_detection', '0009_auto_20210528_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='sample_rate',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
