# Generated by Django 3.1.6 on 2021-06-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apnea_detection', '0012_auto_20210611_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocessing',
            name='dataset',
            field=models.CharField(choices=[('dreams', 'DREAMS Apnea database'), ('dublin', 'University College of Dublin Database'), ('mit', 'MIT-BIH Arrhythmia Database'), ('patch', 'Neurostim Patch data')], default='DREAMS', max_length=20),
        ),
    ]
