# Generated by Django 3.1.6 on 2021-06-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apnea_detection', '0013_auto_20210615_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelHyperParams',
        ),
        migrations.DeleteModel(
            name='Preprocessing',
        ),
    ]
