# Generated by Django 3.2.4 on 2021-06-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apnea_detection', '0014_auto_20210622_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='apnea_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='dataset',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='excerpt',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='sample_rate',
            field=models.PositiveIntegerField(blank=True, default=8),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='scale_factor',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
