# Generated by Django 3.1.6 on 2021-06-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apnea_detection', '0015_auto_20210622_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatlineDetectionParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatline_thresh', models.FloatField(blank=True, default=10)),
                ('low_thresh', models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=3)),
                ('high_thresh', models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=3)),
            ],
        ),
    ]
