# Generated by Django 3.1.6 on 2021-06-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apnea_detection', '0016_flatlinedetectionparams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='excerpt',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
